"""
Customer Exporter Module
========================

Handles generation of per-customer invoice files.

Creates one Excel file per customer containing:
- Invoice cover sheet
- Charge summary
- Detail pivot table
- Shipment information

Handles both special customers (with specific invoice formats)
and general customers.
"""

from pathlib import Path
from typing import Set, Tuple
import pandas as pd

from config import SPECIAL_CUSTOMERS
from utils.helpers import is_blank


class CustomerExporter:
    """
    Per-customer invoice exporter.
    
    Generates one Excel file per customer with:
    - Invoice: Cover sheet with customer ID, batch, and total
    - Charge Summary: AR amounts by charge category
    - Detail: Pivot table of charges by shipment/package
    - ShpInf: Shipment and package information
    
    Handles two customer types:
    - Special customers: Use raw CSV extraction with account codes
    - General customers: Use standardized template with AR calculations
    """

    def __init__(self, base_exporter):
        """
        Initialize customer exporter.
        
        Args:
            base_exporter: Parent UpsInvoiceExporter instance
        """
        self.base = base_exporter

    def generate_customer_invoices(self):
        """
        Generate invoices for all customers (both special and general).
        
        Creates one Excel file per customer in output directory:
        - Special customers: {cust_id}_{batch_number}.csv
        - General customers: {cust_id}_{batch_number}.xlsx
        """
        self.base._ensure_flattened()
        self._generate_special_customer_invoices()
        self._generate_general_customer_invoices()

    def _build_special_keys(self, cid: str) -> Tuple[Set[str], Set[str]]:
        """
        Build key sets (lead shipment numbers and tracking numbers)
        for a special customer.
        
        Args:
            cid: Customer ID
            
        Returns:
            Tuple of (lead_shipment_numbers, tracking_numbers)
        """
        if cid in SPECIAL_CUSTOMERS:
            sub = self.base.flat_packages[self.base.flat_packages["cust_id"] == cid]
            lead_nums = set(sub["Lead Shipment Number"].dropna().astype(str).unique())
            trk_nums = set(sub["Tracking Number"].dropna().astype(str).unique())
            return lead_nums, trk_nums
        return set(), set()

    def _generate_special_customer_invoices(self):
        """
        Generate invoices for special customers.
        
        Special customers are defined in config.SPECIAL_CUSTOMERS.
        Their invoices are generated by:
        1. Extracting raw CSV rows matching their account codes
        2. Extracting raw CSV rows matching their lead/tracking numbers
        
        Output: {cust_id}_{batch_number}.csv with original column headers
        """
        if not self.base.raw_path or not self.base.raw_path.exists():
            print("⚠️ Raw invoice path not provided or doesn't exist. Skipping special customer invoices.")
            return

        tried_encs = ["utf-8", "utf-8-sig", "cp1252", "latin1"]
        header_path = Path(__file__).resolve().parent.parent / "data" / "mappings" / "OriHeadr.csv"
        
        if not header_path.exists():
            print(f"⚠️ Header file not found: {header_path}. Skipping special customer invoices.")
            return

        headers = pd.read_csv(header_path)
        header_list = headers["Column Name"].tolist()

        # Build once from flat_packages for speed
        if self.base.flat_packages.empty:
            print("⚠️ No packages to derive keys from.")
            return

        for cid, meta in SPECIAL_CUSTOMERS.items():
            acct_codes = set(meta.get("accounts", []))

            # Get lead/trk sets for THIS cid from flat_packages
            lead_set, trk_set = self._build_special_keys(cid)

            dfs = []

            for file in self.base.raw_path.glob("*.csv"):
                fname = file.name

                # Case 1: whole file belongs to this special customer by account code in filename
                has_acct = any(ac in fname for ac in acct_codes) or any(
                    len(fname) >= 21 and fname[15:21] == ac for ac in acct_codes
                )

                # Read raw with no headers for both branches to keep shape consistent
                df = None
                for enc in tried_encs:
                    try:
                        df = pd.read_csv(file, header=None, dtype=str, encoding=enc, low_memory=False)
                        break
                    except UnicodeDecodeError:
                        continue
                    except Exception as e:
                        print(f"⚠️ Could not read {fname} with {enc}: {e}")
                        break

                if df is None:
                    print(f"❌ Skipped {fname}: unable to decode with {tried_encs}")
                    continue

                if has_acct:
                    dfs.append(df)
                    continue

                # Case 2: general invoices — select only rows whose col14/col21 match our keys
                if df.shape[1] >= 21:
                    lead_col, trk_col = 13, 20
                    df.iloc[:, lead_col] = df.iloc[:, lead_col].astype(str).str.strip()
                    df.iloc[:, trk_col] = df.iloc[:, trk_col].astype(str).str.strip()
                    mask = df.iloc[:, lead_col].isin(lead_set) | df.iloc[:, trk_col].isin(trk_set)
                    sub_rows = df.loc[mask]
                    if not sub_rows.empty:
                        dfs.append(sub_rows)

            if not dfs:
                # Nothing matched for this special customer — skip quietly
                continue

            combined_inv = pd.concat(dfs, ignore_index=True)
            output_path = self.base.output_path / f"{cid}_{self.base.batch_number}.csv"
            combined_inv.fillna("").replace("nan", "").to_csv(
                output_path, header=header_list, index=False
            )
            print(f"📁 Customer invoice exported: {output_path}")

    def _generate_general_customer_invoices(self):
        """
        Generate invoices for general (non-special) customers.
        
        Creates one Excel file per customer with:
        - Invoice: Cover sheet (Customer ID, Batch Num, Charge Total)
        - Charge Summary: AR amounts by charge category
        - Detail: Pivot table of charges by shipment/tracking
        - ShpInf: Shipment and package information
        
        Output: {cust_id}_{batch_number}.xlsx
        """
        ar_lines_all = self.base.flat_charges.copy()
        ar_lines_all = ar_lines_all[~ar_lines_all["Lead Shipment Number"].apply(is_blank)]
        ar_lines_all = ar_lines_all[ar_lines_all["ar_amt"] != 0]

        pkg_all = self.base.flat_packages.copy()

        # Get all customer IDs
        cust_ids = sorted(
            set(ar_lines_all.get("cust_id", pd.Series(dtype=str)).dropna().unique())
            | set(pkg_all.get("cust_id", pd.Series(dtype=str)).dropna().unique())
        )

        # Exclude special customers
        normal_custs = [c for c in cust_ids if c not in SPECIAL_CUSTOMERS]

        for cid in normal_custs:
            ar_sub = ar_lines_all[ar_lines_all["cust_id"] == cid].copy()
            pkg_sub = (
                pkg_all[pkg_all["cust_id"] == cid].copy()
                if not pkg_all.empty
                else pd.DataFrame()
            )

            # AR Summary
            if not ar_sub.empty:
                ar_summary = (
                    ar_sub.groupby("Charge_Cate_CN", as_index=False)["ar_amt"]
                    .sum()
                    .sort_values("ar_amt", ascending=False)
                    .rename(columns={"Charge_Cate_CN": "费用类型（中文）", "ar_amt": "金额"})
                )
                grand_total = round(float(ar_sub["ar_amt"].sum()), 2)
            else:
                ar_summary = pd.DataFrame(columns=["费用类型（中文）", "金额"])
                grand_total = 0.00

            # Cover sheet
            cover = pd.DataFrame({
                "Field": ["Customer ID", "Batch Num", "Charge Total"],
                "Value": [cid, self.base.batch_number, grand_total],
            })

            # AR Pivot (detail)
            # 1. Pivot table
            pivot_df = ar_sub.pivot_table(
                index=["Lead Shipment Number", "Tracking Number"],
                columns="Charge_Cate_CN",
                values="ar_amt",
                aggfunc="sum",
                fill_value=0
            ).reset_index()
            pivot_df["Package Total"] = pivot_df.drop(
                columns=["Lead Shipment Number", "Tracking Number"]
            ).sum(axis=1)

            # Add grand total row
            col_totals = (
                pivot_df.drop(columns=["Lead Shipment Number", "Tracking Number"])
                .sum(axis=0)
                .to_frame()
                .T
            )
            col_totals.insert(0, "Lead Shipment Number", "Grand Total")
            col_totals.insert(1, "Tracking Number", "")
            pivot_df = pd.concat([pivot_df, col_totals], axis=0)

            # 2. Ensure "运费" (transportation fee) is the first charge column
            cols = pivot_df.columns.tolist()
            if "运费" in cols:
                cols.remove("运费")
                cols = cols[:2] + ["运费"] + cols[2:]
            pivot_df = pivot_df[cols]

            # 3. Reset index for export
            pivot_df = pivot_df.reset_index(drop=True)

            # Shipment Info
            # Drop unnecessary columns
            cols_to_drop = [
                "cust_id", "Invoice Number", "Invoice Date",
                "Length (cm)", "Width (cm)", "Height (cm)"
            ]
            pkg_sub = pkg_sub.drop(columns=cols_to_drop, errors="ignore")

            # Write to Excel
            out = self.base.output_path / f"{cid}_{self.base.batch_number}.xlsx"
            with pd.ExcelWriter(out, engine="xlsxwriter") as w:
                cover.fillna("").replace("nan", "").to_excel(
                    w, sheet_name="Invoice", index=False
                )
                ar_summary.to_excel(
                    w, sheet_name="Charge Summary", index=False
                )
                pivot_df.fillna("").replace("nan", "").to_excel(
                    w, sheet_name="Detail", index=False
                )
                (
                    pkg_sub if not pkg_sub.empty
                    else pd.DataFrame(columns=["（no packages）"])
                ).fillna("").replace("nan", "").to_excel(
                    w, sheet_name="ShpInf", index=False
                )

            print(f"📁 Customer invoice exported: {out}")
